In [22]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns

In [23]:
data=sns.load_dataset('iris')
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
data['species']=data['species'].map(dict((y,x) for x,y in enumerate(data['species'].unique(),0)))

In [25]:
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [26]:
x=data.iloc[:,:-1]
y=data['species']
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y,shuffle=True,random_state=7)

In [27]:
logreg1=LogisticRegression()
logreg1.fit(x_train1,y_train1)
logreg1.score(x_train1,y_train1)

0.9910714285714286

In [28]:
logreg1.coef_

array([[-0.42147635,  0.83265911, -2.27335054, -0.98825112],
       [ 0.33451214, -0.70718965, -0.12538597, -0.83654348],
       [ 0.0869642 , -0.12546946,  2.39873651,  1.8247946 ]])

In [29]:
logreg1.intercept_

array([  9.23878405,   3.83876902, -13.07755307])

In [81]:
from sklearn.datasets import make_classification
data1=make_classification(100,7,random_state=102)
x=data1[0]
y=data1[1]

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,shuffle=True,random_state=27)

In [83]:
logreg=LogisticRegression(penalty='none')
logreg.fit(x_train,y_train)
logreg.score(x_train,y_train)

0.8266666666666667

In [84]:
logreg.intercept_

array([-0.20376197])

In [85]:
logreg.coef_

array([[ 0.68419798, -0.0254034 ,  1.15608493,  0.07849724, -0.09098194,
         0.24861825,  0.39409049]])

In [86]:
def lr_gradien_descent(x,y,eta=0.001,max_iter=100,tol=0.001):
    from numpy import exp
    X=np.c_[np.ones(x.shape[0]),x]
    theta=np.zeros(X.shape[1]).reshape(-1,1)
    if max_iter!=None:
        for i in range(max_iter):
            pred=X@theta
            sig=1/(1+exp(-pred))
            derv=(X.T@(sig-y.reshape(-1,1))).reshape(-1,1)
            theta=theta-eta*derv
    elif max_iter==None:
        mag=100
        while mag>=tol:
            pred=X@theta
            sig=1/(1+exp(-pred))
            derv=(X.T@(sig-y.reshape(-1,1))).reshape(-1,1)
            theta=theta-eta*derv
            mag=np.sqrt(np.sum(derv**2))
    return theta

In [87]:
lr_gradien_descent(x_train,y_train,eta=0.002,max_iter=1000).flatten()

array([-0.20376648,  0.6841685 , -0.02540295,  1.15608405,  0.07854148,
       -0.09097268,  0.24862789,  0.39408933])

In [88]:
lr_gradien_descent(x_train,y_train,eta=0.002,max_iter=None,tol=0.01).flatten()

array([-0.20399922,  0.68305628, -0.02538319,  1.15583697,  0.08044301,
       -0.09047888,  0.24889936,  0.39397666])

In [89]:
pred_data=np.c_[np.ones(x_train.shape[0]),x_train]

In [39]:
from numpy import exp
pred_train=1/(1+exp(-(pred_data@lr_gradien_descent(x_train,y_train,eta=0.002,max_iter=None,tol=0.01).flatten().reshape(-1,1))))

In [40]:
np.where(pred_train>=0.5,1,0).flatten()

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1])

In [41]:
logreg.predict(x_train)

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1])

In [42]:
(np.where(pred_train>=0.5,1,0).flatten()==logreg.predict(x_train)).all()

True